name: Sync SAP CPI iFlow

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      packageId:
        description: "Package ID"
        required: true
        type: string

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Get OAuth Token
        id: oauth
        run: |
          TOKEN=$(curl -s \
            --request POST \
            "${{ secrets.TOKEN_URL }}" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "grant_type=client_credentials" \
            --data-urlencode "client_id=${{ secrets.CLIENT_ID }}" \
            --data-urlencode "client_secret=${{ secrets.CLIENT_SECRET }}" \
            | jq -r '.access_token')

          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Verify Token
        run: |
          if [ -z "$TOKEN" ]; then
            echo "OAuth Token not generated"
            exit 1
          fi

          echo "OAuth Token generated successfully."

      - name: Get Package Details
        run: |
          curl --fail \
            --location \
            --header "Authorization: Bearer $TOKEN" \
            "${{ secrets.BASE_URL }}/api/v1/IntegrationPackages('${{ github.event.inputs.packageId }}')"

      - name: Download Package
        run: |
          mkdir -p iflows

          curl --fail \
            --location \
            --header "Authorization: Bearer $TOKEN" \
            "${{ secrets.BASE_URL }}/api/v1/IntegrationPackages('${{ github.event.inputs.packageId }}')/\$value" \
            --output iflows/package.zip

      - name: Show Downloaded Files
        run: |
          ls -la
          ls -la iflows

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit Changes
        run: |
          git add .

          if git diff --cached --quiet; then
            echo "No changes detected."
          else
            git commit -m "Sync SAP CPI Package"
          fi

      - name: Push Changes
        run: |
          git push origin HEAD:${{ github.ref_name }}
