name: Sync Any iFlow

on:
  workflow_dispatch:
    inputs:
      packageId:
        description: 'Package ID'
        required: true

      directory:
        description: 'Target Git directory (relative from repository root)'
        required: true

      includedIds:
        description: 'Included IDs (optional)'
        required: false

      excludedIds:
        description: 'Excluded IDs (optional)'
        required: false

      draft:
        description: 'Draft handling (optional) - SKIP (default), ADD, ERROR'
        required: false

      dirNaming:
        description: 'Naming convention for iFlow directories (optional) - ID (default), NAME'
        required: false

      message:
        description: 'Commit message (optional)'
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest

    container:
      image: engswee/flashpipe:2.x.x-lite

    env:
      HOST_TMN: inccpidev.it-cpi001.cfapps.eu10.hana.ondemand.com
      HOST_OAUTH: inccpidev.authentication.eu10.hana.ondemand.com
      HOST_OAUTH_PATH: /oauth/token

      OAUTH_CLIENTID: ${{ secrets.CLIENT_ID }}
      OAUTH_CLIENTSECRET: ${{ secrets.CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v2

      - name: Set GIT_SRC_DIR
        run: |
          echo "GIT_SRC_DIR=${GITHUB_WORKSPACE}/${{ github.event.inputs.directory }}" >> $GITHUB_ENV

      - name: Sync Any iFlows
        run: /usr/bin/sync_to_git_repository.sh
        shell: bash
        env:
          PACKAGE_ID: ${{ github.event.inputs.packageId }}
          INCLUDE_IDS: ${{ github.event.inputs.includedIds }}
          EXCLUDE_IDS: ${{ github.event.inputs.excludedIds }}
          DRAFT_HANDLING: ${{ github.event.inputs.draft }}
          DIR_NAMING_TYPE: ${{ github.event.inputs.dirNaming }}
          COMMIT_MESSAGE: ${{ github.event.inputs.message }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
