name: Sync SAP CPI Package

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      packageId:
        description: "Enter SAP Package ID"
        required: true
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Read Previous Sync State
      - name: Read Previous Sync State
        shell: bash
        run: |

          echo "===================================="
          echo "Checking Previous Sync State"
          echo "===================================="

          if [ -f sync-state.json ]; then
            echo "Previous Sync State Found"
            cat sync-state.json
            
          else
            echo "No Previous Sync State Found"
            echo "{}" > sync-state.json
          fi

      # Install jq
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Verify Secrets
      - name: Verify Secrets
        run: |
          echo "TOKEN_URL: ${{ secrets.TOKEN_URL }}"
          echo "CLIENT_ID length: ${#CLIENT_ID}"
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}

      # Generate OAuth Token
      - name: Generate OAuth Token
        env:
          TOKEN_URL: ${{ secrets.TOKEN_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        shell: bash
        run: |

          RESPONSE=$(curl -s -X POST "$TOKEN_URL" \
            -u "$CLIENT_ID:$CLIENT_SECRET" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials")

          echo "$RESPONSE"

          TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')

          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
            echo "OAuth Token generation failed."
            exit 1
          fi

          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      # Get Artifacts from Package
      - name: Get Package Artifacts
        shell: bash
        run: |

          RESPONSE=$(curl -s \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/json" \
            "${{ secrets.BASE_URL }}/api/v1/IntegrationPackages('${{ github.event.inputs.packageId }}')/IntegrationDesigntimeArtifacts")

          echo "$RESPONSE"

          echo "$RESPONSE" > artifacts.json

      # Extract All Artifacts
      - name: Extract All Artifacts
        shell: bash
        run: |

          echo "===================================="
          echo "Artifacts Found"
          echo "===================================="

          jq -r '.d.results[] | "\(.Id) | \(.Version)"' artifacts.json

      # Download All Artifacts
      - name: Download All Artifacts
        shell: bash
        run: |

          mkdir -p iflows

          echo "===================================="
          echo "Downloading All Artifacts"
          echo "===================================="

          jq -c '.d.results[]' artifacts.json | while read artifact
          do

            ID=$(echo "$artifact" | jq -r '.Id')
            VERSION=$(echo "$artifact" | jq -r '.Version')

            echo ""
            echo "Downloading Artifact : $ID"
            echo "Version             : $VERSION"

            curl -L \
              -H "Authorization: Bearer $TOKEN" \
              "${{ secrets.BASE_URL }}/api/v1/IntegrationDesigntimeArtifacts(Id='${ID}',Version='${VERSION}')/\$value" \
              --output "iflows/${ID}.zip"

            if [ $? -eq 0 ]; then
              echo "✅ Successfully downloaded $ID.zip"
            else
              echo "❌ Failed to download $ID"
            fi

          done

          echo ""
          echo "===================================="
          echo "Download Completed"
          echo "===================================="
      # Create Sync State
      - name: Create Sync State
        shell: bash
        run: |

          echo "===================================="
          echo "Creating sync-state.json"
          echo "===================================="

          jq '
            .d.results
            | map({(.Id): .ModifiedAt})
            | add
          ' artifacts.json > sync-state.json

          echo ""

          cat sync-state.json
          
      # Show Files
      - name: Show Files
        run: |
          ls -R

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Commit
      - name: Commit Changes
        run: |

          git add .

          if git diff --cached --quiet; then
            echo "No changes detected."
          else
            git commit -m "Downloaded SAP CPI Artifact"
          fi

      # Push
      - name: Push Changes
        run: |
          git push
